### ISSUE TITLE
how to run this in portainer with a docker-compose file?

### ISSUE THREAD

**Issue by Kamikaze01git** [taylorbobaylor/TrailerDownloader#41]
Hello and thank you very much for this brilliant work!!

Unfortunately, I used to installing Docker via portainer or another GUI and therefore i need a docker compose file...
I don't want to do this via the shell on my Synology NAS :-/

What would this look like? :)

Thank you !!

**Comment by taylorbobaylor** [comment]
Hey! Thanks 😄 

I'm actually running this on synology right now lol. Here's my setup. Let me know if that works for ya! 

```yaml
  trailarr:
    image: taylorbobaylor/movie-trailer-downloader
    container_name: trailarr
    user: root
    volumes:
      - /path/to/movies:/app/movies
    ports:
      - 6767:8080
    restart: always
```

**Comment by Kamikaze01git** [comment]
Hello.
Thank you for the quick response :)

Do I really have to run this as root user?
I tried as a user with admin rights, but it did not work...

Normally I have to create a docker folder where all settings are saved and then mount that folder with the config folder of the docker...
some environments like PUID, PGID and/or Timezone
or a network_mode (bridge?),...
and can I use some other ports?

Anyway: if I use your compose, it works... but I stuck at the settings page :( No matter what path I use, I got error, that the movie path is wrong.

I wanted to test it all in volume1/MEDIA/01-MOVIES/Test/

Inside this Test Folder I have copied 10 movies names like in the description: e.g. Movie 01 (2010)

Is there a way to use other names?
Radar names my folders like Movie 01 (2010), but the files itself are named a little bit more complex (with media infos, etc...).

thank u very much so far :)

PS: dont know if this is important, but I don't use PLEX. I want to use your docker just to scan all movie-folders and download the trailers :)

**Comment by Kamikaze01git** [comment]
Hello again :)

Thank u thousand times for your help!!

This is with a user assigned to my admin group
```
version: "3"
services:
  trailarr:
    image: taylorbobaylor/movie-trailer-downloader
    container_name: trailarr
    enviroment:
      - PUID=1026
      - PGID=101
    volumes:
      - /volume1/MEDIA/01-FILME/Test/:/movies
    ports:
      - 6767:8080
    restart: unless-stopped
```
but with this I compose I got error
```
failed to deploy a stack: validating /data/compose/76/docker-compose.yml: services.trailarr Additional property enviroment is not allowed
```


But when I use it with root, it works fine.
Only stuck at the settings page, because no path is valid :(
```
version: "3"
services:
  trailarr:
    image: taylorbobaylor/movie-trailer-downloader
    container_name: trailarr
    user: root
    volumes:
      - /volume1/MEDIA/01-FILME/Test/:/movies
    ports:
      - 6767:8080
    restart: unless-stopped
```
